services:
  - type: web
    name: jorjek-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/server.js
    plan: free
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: PORT
        value: 4000
      - key: CADT_EMAIL_DOMAIN
        value: "@student.cadt.edu.kh"
      - key: NOTIFICATION_TRANSPORT
        value: websocket
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
